TOPOJSON = node_modules/.bin/topojson
TOPOMERGE = node_modules/.bin/topojson-merge

all:

#
# Statistical Local Areas ASGC Ed 2011 Digital Boundaries in ESRI Shapefile Format
#
zip/sla11aaust_shape.zip:
	mkdir -p $(dir $@)
	wget "http://www.abs.gov.au/ausstats/subscriber.nsf/log?openagent&1259030001_sla11aaust_shape.zip&1259.0.30.001&Data%20Cubes&56A7AA594A7F44F9CA2578CC0011CE44&0&July%202011&14.07.2011&Latest" -O $@.download
	mv $@.download $@

#
# Statistical Subdivision ASGC Ed 2011 Digital Boundaries in ESRI Shapefile Format 
#
zip/ssd11aaust_shape.zip:
	mkdir -p $(dir $@)
	wget "http://www.abs.gov.au/ausstats/subscriber.nsf/log?openagent&1259030001_ssd11aaust_shape.zip&1259.0.30.001&Data%20Cubes&4913953D966B9E79CA2578CC0011E833&0&July%202011&14.07.2011&Latest" -O $@.download
	mv $@.download $@

#
# Statistical Division ASGC Ed 2011 Digital Boundaries in ESRI Shapefile Format
#
zip/sd11aaust_shape.zip:
	mkdir -p $(dir $@)
	wget "http://www.abs.gov.au/ausstats/subscriber.nsf/log?openagent&1259030001_sd11aaust_shape.zip&1259.0.30.001&Data%20Cubes&A2521D72ABA3D177CA2578CC0011FBFE&0&July%202011&14.07.2011&Latest" -O $@.download
	mv $@.download $@

#
# State and Territory ASGC Ed 2011 Digital Boundaries in ESRI Shapefile Format 
#
zip/ste11aaust_shape.zip:
	mkdir -p $(dir $@)
	wget "http://www.abs.gov.au/ausstats/subscriber.nsf/log?openagent&1259030001_ste11aaust_shape.zip&1259.0.30.001&Data%20Cubes&D39E28B23F39F498CA2578CC00120E25&0&July%202011&14.07.2011&Latest" -O $@.download
	mv $@.download $@

#
# Statistical District ASGC Ed 2011 Digital Boundaries in ESRI Shapefile Format 
#
zip/sdist11aaust_shape.zip:
	mkdir -p $(dir $@)
	wget "http://www.abs.gov.au/ausstats/subscriber.nsf/log?openagent&1259030001_sdist11aaust_shape.zip&1259.0.30.001&Data%20Cubes&1A91E60D88532CEACA2578CC0012174E&0&July%202011&14.07.2011&Latest" -O $@.download
	mv $@.download $@

#
# Local Government Area ASGC Ed 2011 Digital Boundaries in ESRI Shapefile Format
#
zip/lga11aaust_shape.zip:
	mkdir -p $(dir $@)
	wget "http://www.abs.gov.au/ausstats/subscriber.nsf/log?openagent&1259030001_lga11aaust_shape.zip&1259.0.30.001&Data%20Cubes&03275B7661181087CA2578CC001223EA&0&July%202011&14.07.2011&Latest" -O $@.download
	mv $@.download $@

#
# Statistical Region Sector ASGC Ed 2011 Digital Boundaries in ESRI Shapefile Format 
#
zip/srs11aaust_shape.zip:
	mkdir -p $(dir $@)
	wget "http://www.abs.gov.au/ausstats/subscriber.nsf/log?openagent&1259030001_srs11aaust_shape.zip&1259.0.30.001&Data%20Cubes&97AA197CD16B9D16CA2578CC00123B31&0&July%202011&14.07.2011&Latest" -O $@.download
	mv $@.download $@

#
# Statistical Region ASGC Ed 2011 Digital Boundaries in ESRI Shapefile Format
#
zip/sr11aaust_shape.zip:
	mkdir -p $(dir $@)
	wget "http://www.abs.gov.au/ausstats/subscriber.nsf/log?openagent&1259030001_sr11aaust_shape.zip&1259.0.30.001&Data%20Cubes&B8003880BC09FA5BCA2578CC00124E25&0&July%202011&14.07.2011&Latest" -O $@.download
	mv $@.download $@

#
# Major Statistical Region ASGC Ed 2011 Digital Boundaries in ESRI Shapefile Format
#
zip/msr11aaust_shape.zip:
	mkdir -p $(dir $@)
	wget "http://www.abs.gov.au/ausstats/subscriber.nsf/log?openagent&1259030001_msr11aaust_shape.zip&1259.0.30.001&Data%20Cubes&F087093CCDF2C68DCA2578CC0012607E&0&July%202011&14.07.2011&Latest" -O $@.download
	mv $@.download $@

